name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - 'feature/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & test (Maven verify)
        run: mvn -B -DskipTests=false verify

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_number }}
          path: |
            target/*.jar
            target/surefire-reports/**
            target/failsafe-reports/**
            target/checkstyle-result.xml
            target/spotbugsXml.xml
            target/site/jacoco/**
          retention-days: 7
