name: release

on:
  push:
    tags:
      - 'v*'   # e.g., v0.1.0

permissions:
  contents: write   # needed to create a GitHub Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Extract version from tag
        id: vars
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Set project version to tag
        run: mvn -B versions:set -DnewVersion='${{ steps.vars.outputs.version }}' -DgenerateBackupPoms=false

      - name: Build shaded JAR + Javadoc
        run: |
          mvn -B -P release -DskipTests=false package
          mvn -B javadoc:javadoc

      - name: Compute checksums
        run: |
          cd target
          for f in *.jar; do sha256sum "$f" > "$f.sha256"; done

      - name: Zip Javadoc
        run: |
          cd target/site
          zip -r apidocs.zip apidocs

      - name: Generate simple release notes
        run: |
          set -e
          PREV=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || true)
          if [ -n "$PREV" ]; then RANGE="$PREV..HEAD"; else RANGE="$(git rev-list --max-parents=0 HEAD)..HEAD"; fi
          git log --pretty=format:'- %s (%h)' $RANGE > RELEASE_NOTES.md || echo "- Initial release" > RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ steps.vars.outputs.version }}
          body_path: RELEASE_NOTES.md
          files: |
            target/*.jar
            target/*.jar.sha256
            target/site/apidocs.zip
